name: Deploy product-serverless
on:
  push:
    branches:
      - main

jobs:
  productionDeploy:
    name: production-deploy
    runs-on: ubuntu-latest
    environment:
      name: prod
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Transpile fetchNotion.js
      run: |
        npm install --save-dev @babel/cli @babel/core @babel/preset-env
        npx babel fetchNotion.js --out-dir lib
    - name: Install Plugin and Deploy
      uses: serverless/github-action@v4
      with:
        args: -c "serverless plugin install --name serverless-dotenv-plugin && serverless plugin install --name serverless-offline && serverless deploy --stage prod"
        entrypoint: /bin/sh
      env:
        NOTION_KEY: ${{ secrets.NOTION_KEY }}
        NOTION_DB: ${{ secrets.NOTION_DB }}